version: "3.2"
services:
  jenkins:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ${HOME}/jenkins/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID}
      - JENKINS_ADMIN_SECRET=${JENKINS_ADMIN_SECRET}
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - DOCKER_API_IP=${DOCKER_API_IP}
      - DOCKER_API_PORT=${DOCKER_API_PORT}
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yml
